services:
  - type: web
    name: tg-mus-bot
    env: python
    region: frankfurt
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 main.py"
    runtime:
      python: 3.11.9
